#!/bin/bash

if [ "$#" -lt 1 ]; then
        find ./tests -name *.in | sort | xargs $0
fi

for arg in "$@"; do
        arg=${arg##*/}
        arg=${arg%.*}
        echo -e "\e[1;37m"$arg".in:\e[21m"
        cat tests/"$arg".in
        echo

        echo -e "\e[1;37moutput:\e[21m"
        sdiff results/"$arg".obs.out results/"$arg".exp.out
        echo -e "\e[39m"
done